### ISSUE TITLE
Unable to enter in chat window 

### ISSUE THREAD

**Issue by shaheenshaikh6** [QuickBlox/quickblox-react-native-samples#1]
Hi Team,
I successfully installed youe sample code for chatting, but unable to go after login screen as getting error notification "Failed to update user". Please check

**Comment by bhoomika-sorathiya** [comment]
I am also facing the same issue. Can anyone please help here?

**Comment by mrcarjul** [comment]
The issue is due to NotificationService.js file a function setupPushNotifications is trying to retrieve info from gServices which is imported by google-services.json which  is commented,you can just comment the call to this function in Login.jsx or add the google services config for push notifications

**Comment by dheereshaggarwal** [comment]
@mrcarjul yeah, thanks man, it worked, just restart all the processes after commenting the call in Login.jsx otherwise it won't work

**Comment by QB-nikolay-zolotarov** [comment]
@shaheenshaikh6 @bhoomika-sorathiya 
Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Comment by QB-nikolay-zolotarov** [comment]
@shaheenshaikh6 @bhoomika-sorathiya 
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.
