### ISSUE TITLE
Audio/Video call connection issue on react native iOS

### ISSUE THREAD

**Issue by sayalichaware** [QuickBlox/quickblox-react-native-samples#46]
Hello developer,
We have the website which include the javascript sdk of quickblox and the app with react native sdk. Audio or Video call is not getting connected when we have called iOS app user from the website user.  It works when we call website user from app.

For android platfom it works in both the cases.

Using latest sdk in App.

Please help to provide a solution.

Thanks

**Comment by VladimirNybozhinsky** [comment]
@sayalichaware 
This is Vladimir from QuickBlox.

Please try to reproduce the issue on our clear [JS_WebRTC_Sample](https://github.com/QuickBlox/quickblox-javascript-sdk) and clear [RN_WebRTC_Sample (IOS)](https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/webrtc-sample)
If the issue is reproduced, please provide us with the steps.
You can learn how to enable the logs here: https://help.quickblox.com/article/368-how-can-i-enable-quickblox-logs.

**Comment by sayalichaware** [comment]
Hello developer,

Can we delete or clear the conversation between two users. (Private dialog)?

**Comment by VladimirNybozhinsky** [comment]
[@sayalichaware](https://github.com/sayalichaware), this is Vladimir from QuickBlox. 
The steps to delete a private conversation between two users are described in the QuickBlox documentation under the [Dialogs | Chat | React Native SDK](https://docs.quickblox.com/docs/react-native-chat-dialogs#delete-dialog) section. You can also view an implementation of this case in our [RN Chat Sample](https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/chat-sample) repository located at quickblox-react-native-samples/chat-sample on the QuickBlox GitHub page.
