### ISSUE TITLE
Phone Overheats During Videocall

### ISSUE THREAD

**Issue by stephanoparaskeva** [QuickBlox/quickblox-react-native-samples#8]
After around 25 minutes phones begin overheating:

First Phone: *Iphone 12*
Second Phone: *Iphone 8*

Before I started the call with 15% battery.
Battery current: less than ~300 ma
Battery temperature - ~36 C
~3 min into the call -
2 % battery Consumed, the phone was heated up
Battery current: 1065 ma
Battery Temp: 41.4 C

~5 min into the call - 5% battery consumed, the phone was super hot
Battery Current: 1554 ma
battery temp: 44.8 C.

**Comment by QB-nikolay-zolotarov** [comment]
@stephanoparaskeva Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant.

If yes, please provide me with the following points:
1. Version of QuickBlox React Native SDK.
2. iOS versions.
3. React Native version.
4. Information from react-native info.
5. Information from npm list.
6. Please clarify if you used our React Native Video calling sample: 
[https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/webrtc-sample](https://github.com/QuickBlox/quickblox-react-native-samples/tree/master/webrtc-sample)
